AWSTemplateFormatVersion: '2010-09-09'
Description: IAC RDS

Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS
      SubnetIds:
        - subnet-045e30c0f3191fd64
        - subnet-088d6892c8c01ca52
  ## Security Group
  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow connections only from Webserver
      Tags:
        - Key: Name
          Value: "sg-app-voting"
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 5432
        ToPort: 5432
        SourceSecurityGroupId: !GetAtt EC2SecurityGroup.GroupId

  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: postgres
      EngineVersion: "15.6"
      DBInstanceClass: db.t4g.micro	
      DBInstanceIdentifier: db-app-voting
      DBName: votes
      MasterUsername: adatech
      MasterUserPassword: Pdokdfo343534ddsa
      PerformanceInsightsRetentionPeriod: 7
      EnablePerformanceInsights: true
      AllocatedStorage: 5
      #DBParameterGroupName: !Ref RDSParameterGroup
      VPCSecurityGroups:
        - Fn::GetAtt: [ DBSecurityGroup, GroupId ]

  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for RDS access
      VpcId: vpc-0350e7411ef49ece9
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432  
          ToPort: 5432
          CidrIp: 172.31.0.0/16
